---
- name: Download web
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  tags: without-postgres


- name: Install pgsql
  yum:
    name: postgresql14-server
  tags: without-postgres
  
  
# - name: "Initialize PostgreSQL"
#   shell: "/usr/pgsql-14/bin/postgresql-14-setup initdb"
#   tags: init

- name: Postgresql-stop
  systemd:
    name: postgresql-14.service
    state: stopped
    
- name: WAL
  file: path=/wal state=directory recurse=yes owner=postgres group=postgres

- name: MODE-var/lib/pgsql
  ansible.builtin.file:
    path: /var/lib/pgsql/14/data
    state: directory
    recurse: yes
    owner: postgres
    group: postgres


# - name: create ROLE replicant
#   postgresql_user:
#     db: postgres
#     login_unix_socket: /var/run/postgresql
#     name: replicant
#     password: replicant
#     role_attr_flags: LOGIN,REPLICATION


# - name: BaseBackup
#   shell: "pg_basebackup -h 192.168.14.114 -D /var/lib/pgsql/14/data -R -P -U replicant -X stream" 










    
    
