---
- name: Mount an NFS volume
  ansible.posix.mount:
    src: 192.168.100.100:/srv/backup
    path: /pgsql/pg_backup
    state: mounted
    fstype: nfs

- name: rpm-packet
  yum:
    name: https://repo.postgrespro.ru/pg_probackup/keys/pg_probackup-repo-centos.noarch.rpm
  tags: rpm-probackup
  
- name: install probackup
  yum: 
    name: pg_probackup-14
    state: installed
  tags: install probackup


#-------------------------только на одном из серверов

- name: init /pgsql/pg_backup
  shell: 'pg_probackup-14 init -B /pgsql/pg_backup/'
  when: "'pg1' in inventory_hostname"

- name: add-instaled
  shell: 'pg_probackup-14 add-instance -B /pgsql/pg_backup/ -D /pgsql/pg_data/14/ --instance sirius '
  when: "'pg1' in inventory_hostname"

#--------------------------------------------------

- name: copy backup.sql
  template:
    scr: backup.sql
    dest: /pgsql/pg_backup/backup.sql
  when: '"pg2" in inventory_hostname'


# - name: pgsql backup.sql
#   shell: 'psql -f /pgsql/pg_backup/backup.sql'
#   become_user: postgres
#   become: yes
#   when: '"pg2" in inventory_hostname'

# - name: Backup
#   shell: 'pg_probackup-14 backup -B /pgsql/pg_backup --instance sirius -b FULL'
#   become_user: postgres
#   become: yes
#   when: '"pg2" in inventory_hostname'