---
- name: playbook for nfs
  hosts: 
    - nfs
  roles: 
    - roles/nfs
  tags: playbook
  
- name: prepare pg1/pg2 postgresql14
  hosts: 
    - pgsql
  roles:
    - roles/prepare-pgsql
  tags: pb-prepare-pgsql





 

